### ISSUE TITLE
This isn't properly done.

### ISSUE THREAD

**Issue by santostiago** [Vizzuality/forest-atlas-landscape-cms#268]
https://github.com/Vizzuality/forest-atlas-landscape-cms/blob/e137ebb53e21cd634f90048d043fcd2a37f2e343/app/controllers/site_page_controller.rb#L31-L39

I'm not really sure what you need here, and I fixed it just so it doesn't crash, but I'm quite sure this isn't doing anything

**Comment by tomasmoose** [comment]
@santostiago we dont need this variable anymore, lets just remove the reference all together ! 

`gon.content` is not required to be set anymore !

**Comment by tomasmoose** [comment]
Removed, closing
